version: '3.3'

services:
  web:
    build: .
    container_name: store_image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: 'postgres:12'
    hostname: postgres
    container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
    ports:
      - '5432:5432'

